### ISSUE TITLE
Clean up the code

### ISSUE THREAD

**Issue by Huy-Ngo** [Huy-Ngo/skin-crawler#28]
The current backend code was written in a rushed manner due to the deadlines so it is not very clean and of bad quality. Let's refactor it after #26 is merged.

**Comment by dinhanhx** [comment]
- [x] Clean yandex module (#26)

- [x] Clean wikimedia module (#32)

- [x] Clean kaggle module (#32)

- [x] Clean isic module (#32)

- [x] Rewrite static crawler (#32)
